name: Handle migration commands

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

jobs:
  handle-command:
    if: |
      contains(github.event.comment.body, '/cutover') ||
      contains(github.event.comment.body, '/archive') ||
      contains(github.event.comment.body, '/remigrate') ||
      contains(github.event.comment.body, '/migrate') ||
      contains(github.event.comment.body, '/dryrun') ||
      contains(github.event.comment.body, '/test')
    runs-on: ubuntu-latest

    steps:
      - name: Extract command and snow ID
        id: extract
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          COMMAND=$(echo "$COMMENT_BODY" | awk '{print $1}' | sed 's|/||')
          echo "command=$COMMAND" >> "$GITHUB_OUTPUT"

          # Extract SNOW ID if present (e.g., TKT########)
          if [[ "$COMMENT_BODY" =~ TKT[0-9]{8} ]]; then
            SNOW_ID=$(echo "$COMMENT_BODY" | grep -oE 'TKT[0-9]{8}')
            echo "snow_id=$SNOW_ID" >> "$GITHUB_OUTPUT"
          fi

      - name: Validate /cutover and /archive format
        id: validate
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
          COMMAND: ${{ steps.extract.outputs.command }}
        run: |
          if [[ "$COMMAND" == "cutover" || "$COMMAND" == "archive" ]]; then
            if [[ "$COMMENT_BODY" =~ ^/(cutover|archive)[[:space:]]+TKT[0-9]{8}$ ]]; then
              echo "valid=true" >> "$GITHUB_OUTPUT"
            else
              echo "valid=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "valid=true" >> "$GITHUB_OUTPUT"  # Always valid for other commands
          fi

      - name: Comment on issue if invalid
        if: steps.validate.outputs.valid == 'false'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ⚠️ **Invalid command format.**

            ✅ **Correct format examples:**
            ```
            /cutover TKT63652208
            /archive TKT63679901
            ```

            ❓ Must start with `/cutover` or `/archive` followed by a space and a valid `TKT` number (8 digits).

      - name: Exit if command is invalid
        if: steps.validate.outputs.valid == 'false'
        run: exit 1

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Create TKT label and add to issue
        if: |
          steps.validate.outputs.valid == 'true' &&
          (steps.extract.outputs.command == 'cutover' || steps.extract.outputs.command == 'archive')
        uses: actions/github-script@v7
        with:
          script: |
            const snowId = "${{ steps.extract.outputs.snow_id }}";
            const issueNumber = context.payload.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            try {
              await github.rest.issues.getLabel({ owner, repo, name: snowId });
              console.log(`Label '${snowId}' already exists.`);
            } catch (error) {
              if (error.status === 404) {
                await github.rest.issues.createLabel({
                  owner,
                  repo,
                  name: snowId,
                  color: 'ededed',
                  description: 'Auto-generated TKT label'
                });
                console.log(`Label '${snowId}' created.`);
              } else {
                throw error;
              }
            }

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: issueNumber,
              labels: [snowId]
            });
